<?php

define('ADMIN', '1');
define('SCHOOL', '2');
define('TEACHER', '3');
define('TUTOR', '4');
define('PARENT', '4');
define('STUDENT', '5');
define('QUESTIONADMIN', '6');
define('QUESTIONVALIDATOR', '7');
define('ALL', '7');
define('FIRST', 'First Year');
define('SECOND', 'Second Year');
define('THIRD', 'Third Year');
define('PERCENT', '1');
define('DOLLAR', '2');
define('NULL', '');
define('ACTIVE', 'Active');
define('INACTIVE', 'Inactive');
define('DELETED', 'Deleted');
define('numeric_valid', '^[0-9-]+$/i');
define('numeric_space_valid', '^[0-9 ]+$/i');
define('alpha_valid', '[^<>]+$/i');
//define('only_alpha_valid', '^[A-Za-z -]+$/i');
define('only_alpha_valid', '^[ A-Za-z0-9-_&$\']+$/i');
define('alpha_numeric_valid', '^[A-Za-z0-9 ]+$/i');
define('alpha_numeric_no_space_valid', '^[A-Za-z0-9]+$/i');
define('def_number_valid', '^[A-Za-z0-9 \/]+$/i');
define('alpha_special_char', '^[ A-Za-z0-9-_&$\']+$/i');
define('amount_valid', '^[0-9.]+$/i');
define('password_valid', '((?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[_&@#$%^!()-]).{6,})/');
define('UIMG_L_W', 500);
define('UIMG_L_H', 500);
define('UIMG_M_W', 200);
define('UIMG_M_H', 200);
define('UIMG_S_W', 50);
define('UIMG_S_H', 50);
define('OTHER', 'Other');
define('UKCOUNTRYCODE', 'GB');
define('OTHER_VALUE', '-1');
define('UPDATEPROFILE', 'updateprofile');
#define('FROM_EMAIL', 'sanjeev.rajput@icreon.com');
define('FROM_EMAIL', 'vignesh.t@sedinfotech.ch');
define('FROM_NAME', 'SATS Administrator');
#define('CC_EMAIL', 'sanjeev.rajput@icreon.com');
define('CC_EMAIL', 'vignesh.t@sedinfotech.ch');
define('CC_NAME', 'SATS Administrator');
define('img_maxsize', '500');
define('audio_maxsize', '20M');
define('SUCCESS', 'Success');
define('FAIL', 'Fail');
define('SUBSCRIBED', 1);
define('UNSUBSCRIBED', 0);
define('CURRENCY_CODE', 'GBP');
define('YEARLY_SUBS', 'Yearly Subscription');
define('RENEW_YEARLY_SUBS', 'Renewed Subscription');
define('PURCHASE_SUBSCRIPTION', 'Purchase Subscription');
define('NEW_SIGNUP', 'New Sign-Up');
define('NULL_DATETIME', '0000-00-00 00:00:00');
define('MATH', 'Math');
define('MATHS', 'Maths');
define('ENGLISH', 'English');
define('SITE_URL', 'http://' . $_SERVER['SERVER_NAME']);
define('PUBLISH', 'Published');
define('UNPUBLISH', 'Unpublished');
define('DRAFT', 'Draft');
define('REJECT', 'Rejected');
define('INREVIEW', 'In Review');
define('REVISION', 'Revision');
define('CURRENCY', '&pound;');
define('CALENDER_DATE_FORMAT', 'dd/mm/yyyy');
define('TEST', 'Test');
define('WP_URL', 'http://satscompanion.com');
define('LIVE_WP_URL', 'https://demo.satscompanion.com');
define('REVISION_TIME', '2700');
define('REVISION_QUS_LIMIT', '20'); // how many to show randomly
define('DASHBOARD_RECORD_LIMIT', '10');
define('STRAND_GOOD_THRESHOLD', '50');
define('STRAND_PERFORMANCE_LIMIT', '5');
define('STUDENT_REWARD_THUMBNAIL_WIDTH', '200');
define('TUTOR_NO_OF_STUDENTS', '1');
define('NO_OF_STUDENTS', '30');
define('INVOICED', 'Invoiced');
define('PENDING', 'Pending');
define('COMPLETED', 'Completed');
define('INPROGRESS', 'Inprogress');
define('PERCENTAGE', 'Percentage');
define('SCORE', 'Score');
define('REVISION_MIN_QUS_LIMIT', '10'); // minimum question to create a rivision automatically
define('TEST_MIN_QUS_LIMIT', '20'); // not is use
define('POUND_SYMBOL', '£');
define('RECEIPT', 'RECEIPT');
define('INVOICE', 'INVOICE');
define('HEADER_INVOICE', 'Office 10, 162 Tooting High <br>Street, London SW17 0RT<br>sales@satscompanion.com<br>');
define('INVOICE_FOOTER_1', "Thank you for your order,<br/><strong>SATS Companion</strong><br/><br/>Payment due before account activation. Please quote the invoice number above when making payment.");
define('INVOICE_FOOTER_PAID_PAYMENT_1', "Thank you for your order,<br/><strong>SATS Companion</strong><br/><br/>Payment due before account activation. Please quote the invoice number above when making payment.");
define('INVOICE_FOOTER_2', "Payment Methods<br/>"
        . "<u>Post</u> If you're posting your payment, cheques should be made payable to 'SATS Companion'"
        . "<br/><br/><u>BACS</u> Please make BACS payments to SATs Companion Ltd, Lloyds<br/>"
        . "Sort Code: 30-15-95      Account No:   18026068");
define('INVOICE_FOOTER_3', "<b>SATs Companion Ltd</b><br/>Incorporated in England & Wales. Registration Number: 9817536<br/>Registered Office Address: 127 Trinity Road, London SW17 7HJ <br/> Trading Address: Office 10, 162 Tooting High Street, London SW17 0RT");
define('SUPERADMIN_ID',1);
define('WELCOME_MESSAGE_SUBJECT','Welcome to SATs Companion');
define('WELCOME_MESSAGE_MESSAGE','Welcome to SATs Companion! We hope you enjoy the great features we have to offer. If you need any assistance, feel free to email our team at ask@satscompanion.com');